name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Get Package Version
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          echo "Package version: $PACKAGE_VERSION"  # Debugging: print the package version
          echo "::set-output name=version::$PACKAGE_VERSION"

      - name: Get Current Date and Time
        id: get_datetime
        run: |
          CURRENT_DATETIME=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          echo "Current Date and Time: $CURRENT_DATETIME"  # Debugging: print the current date and time
          echo "::set-output name=datetime::$CURRENT_DATETIME"

      # - name: Obtain Access Token
      #   id: get_token
      #   run: |
      #     response=$(curl -X POST https://driverseat-staging.auth.eu-central-1.amazoncognito.com/oauth2/token \
      #     -H "Content-Type: application/json" \
      #     -d '{"grant_type": "client_credentials", "client_id": "7om4hqjn2bnbm079r3u64db64v", "client_secret": "1tlsoi2p5kerqsc3jj923asrbbqptpqcoi0r5enldcrkmqtdmha0"}')
      #     echo "Response: $response"  # Debugging: print the full response
      #     echo "::set-output name=token::$(echo $response | jq -r '.access_token')"

      # - name: Submit new app version
      #   run: |
      #     curl -X 'PUT' \
      #       'https://api-staging.financiallease.nl/versions/FinancialLeaseMobileApp' \
      #       -H 'accept: */*' \
      #       -H 'Authorization: Bearer ${{ steps.get_token.outputs.token }}' \
      #       -H 'Content-Type: application/json' \
      #       -d '{
      #       "platform": "Android",
      #       "version": "2.23.3",
      #       "releasedAt": "${{ steps.get_datetime.outputs.datetime }}"
      #     }'

      # - name: Print Token (for debugging purposes)
      #   run: echo "Access Token: ${{ steps.get_token.outputs.token }}"
