name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Get Package Version
        id: get_version
        run: |
          PACKAGE_VERSION=$(jq -r '.version' package.json)
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT

      - name: Get Current Date and Time
        id: get_datetime
        run: |
          CURRENT_DATETIME=$(date --utc +%Y-%m-%dT%H:%M:%SZ)
          echo "datetime=$CURRENT_DATETIME" >> $GITHUB_OUTPUT

      - name: Obtain Access Token
        id: get_token
        run: |
          response=$(curl --location 'https://driverseat-staging.auth.eu-central-1.amazoncognito.com/oauth2/token/' \
          --header 'Content-Type: application/x-www-form-urlencoded' \
          --header 'Cookie: XSRF-TOKEN=5d9f6e0a-715c-4142-8731-29a17410fb91' \
          --data-urlencode 'grant_type=client_credentials' \
          --data-urlencode 'client_id=7om4hqjn2bnbm079r3u64db64v' \
          --data-urlencode 'client_secret=1tlsoi2p5kerqsc3jj923asrbbqptpqcoi0r5enldcrkmqtdmha0')
          echo "Response: $response"
          access_token=$(echo $response | jq -r '.access_token')
          echo "Access Token: $access_token"
          echo "Access Token Length: ${#access_token}"
          echo "token=$(echo $response | jq -r '.access_token')" >> $GITHUB_OUTPUT


      # - name: Submit new app version - Android
      #   run: |
      #     curl -X 'PUT' \
      #       'https://api-staging.financiallease.nl/versions/FinancialLeaseMobileApp' \
      #       -H 'accept: */*' \
      #       -H 'Authorization: Bearer ${{ steps.get_token.outputs.token }}' \
      #       -H 'Content-Type: application/json' \
      #       -d '{
      #       "platform": "Android",
      #       "version": "${{ steps.get_version.outputs.version }}",
      #       "releasedAt": "${{ steps.get_datetime.outputs.datetime }}"
      #     }'

      # - name: Submit new app version - IOS
      #   run: |
      #     curl -X 'PUT' \
      #       'https://api-staging.financiallease.nl/versions/FinancialLeaseMobileApp' \
      #       -H 'accept: */*' \
      #       -H 'Authorization: Bearer ${{ steps.get_token.outputs.token }}' \
      #       -H 'Content-Type: application/json' \
      #       -d '{
      #       "platform": "IOS",
      #       "version": "${{ steps.get_version.outputs.version }}",
      #       "releasedAt": "${{ steps.get_datetime.outputs.datetime }}"
      #     }'